services:
  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:3.12.6-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=api'
      - 'RABBITMQ_DEFAULT_USER=api'
    ports:
      - '5672:5672'
      - '15672:15672'
