name: Deploy

env:
  GKE_CLUSTER: joshlong-com
  GKE_ZONE: us-central1-c
  BLOG_INDEX_REBUILD_KEY: ${{  secrets.BLOG_INDEX_REBUILD_KEY }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

on:
  push:
    branches: [ main ]


jobs:
  build-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: '${{ env.GKE_CLUSTER  }}'
          location: '${{ env.GKE_ZONE }}'

      - run: |
          gcloud config set project $PROJECT_ID
          gcloud --quiet auth configure-docker
          kubectl get pods

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: joshlong/java-version-export-github-action@v20

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ env.JAVA_MAJOR_VERSION }}

      - name: Deploy Site
        run: |
          cd $GITHUB_WORKSPACE
          export ROOT_DIR=$GITHUB_WORKSPACE
          ./deploy/deploy.sh